### ISSUE TITLE
I'd like to be able to get outcome details

### ISSUE THREAD

**Issue by phpguru** [thephpleague/omnipay-stripe#106]
I don't know exactly where this fits in with the various other omni-pay drivers, but it would be nice to be able to print, on the customer receipt / thank you page, for example, the bank reply; something like

    Message: Payment Complete.  // $charge['data']['outcome']['seller_message']
    Status: approved_by_network  // $charge['data']['outcome']['network_status']
    Type: authorized  // $charge['data']['outcome']['type']

I was thinking of adding a getOutcome method for this purpose, which would be used on `charge` objects. Any reason why the `outcome` sub-node of `$data` has no corresponding getter method?

**Comment by barryvdh** [comment]
Closed in favor of #107

**Comment by phpguru** [comment]
@barryvdh what do you think of something like this?

    /**
     * Obtain any string from the response data using get* accessor method, if it exists,
     * up to two-levels deep within the returned data structure.
     */
    public function __call($method, $args)
    {
        $method = strtlower($method);
        if (preg_match('/^get([a-z0-9]+)$/', $method, $matches)) {
            if (isset($this->data[$matches[1]]) {
                if (isset($args) && 1 === count($args)) {
                    if (isset($this->data[$matches[1]][$args[0]])) {
                        return $this->data[$matches[1]][$args[0]];
                    }
                } else {
                    return $this->data[$matches[1]];
                }
            }
        }

        return null;
    }
