### ISSUE TITLE
Use PaymentIntent

### ISSUE THREAD

**Issue by hpatoio** [thephpleague/omnipay-stripe#118]
I'm about to start to integrate Stripe in my site. I would like to use the new object `PaymentIntent` ( https://stripe.com/docs/payments/payment-intents ) instead of `Source`.

This new object has a series of new features and it support 3DS2.

Does this library supports `PaymentIntent`

**Comment by chemistry-marketing** [comment]
> I'm about to start to integrate Stripe in my site. I would like to use the new object `PaymentIntent` ( https://stripe.com/docs/payments/payment-intents ) instead of `Source`.
> 
> This new object has a series of new features and it support 3DS2.
> 
> Does this library supports `PaymentIntent`

Did you manage to find a solution? I am also looking to add something similar

**Comment by m2de** [comment]
Also keen to find out if the new PaymentIntend will be supported as it will become a requirement for EU payments from September 2019?

**Comment by munagurung** [comment]
Any update?
