### ISSUE TITLE
Paiement Intents not available in latest release

### ISSUE THREAD

**Issue by CreativeBulma** [thephpleague/omnipay-stripe#145]
Hi,

when will paiment intent will be available in the release ?
The current v3.0.2 release does not includes it.

regards

**Comment by bearn666** [comment]
@CreativeBulma hello, as i understand from under the hood of package, you should use $gateway->purchase([...]),
you can check source `.../vendor/omnipay/stripe/src/Message/PaymentIntents/PurchaseRequest.php`.

For example in my case i am using next code:
...->gateway()
                ->purchase([
                    'amount'            => $order->getAttribute('amount'),
                    'currency'          => strtolower($order->currency->code),
                    'description'       => 'Uncaptured charge for ride: ' . $order->id,
                    'confirm'           => $capture,
                    'customerReference' => $customerReference
                ]);

And result of this request i see in my Stripe dashboard

**Comment by barryvdh** [comment]
Tagged 3.1.0

**Comment by CreativeBulma** [comment]
Thanks @barryvdh
