### ISSUE TITLE
Stripe Payment Intents workflow

### ISSUE THREAD

**Issue by 2ec0b4** [thephpleague/omnipay-stripe#146]
👋

I am updating the payment workflow on a website i am working on. I am following the description made in the block [Stripe Payment Intents](https://github.com/thephpleague/omnipay-stripe#stripe-payment-intents) from the README.md file (or from [this comment](https://github.com/thephpleague/omnipay-stripe/issues/122#issuecomment-511719168)) and... I'm lost.

First, the page the link "[collecting the payment method details](https://stripe.com/docs/payments/payment-intents/quickstart#collect-payment-method)" is pointing to has been updated.

Then, on this stripe.com page, they are talking about five steps to create a one-time payment:
1. Create a PaymentIntent (specifying the amount and the currency) on the server
2. Pass `client_secret` to the client, this is an attribute of the PaymentIntent object got from the previous step response
3. Collect payment method details on the client with Stripe.js
4. Submit the payment **to Stripe from the client** with Stripe.js using `stripe.handleCardPayment` method
5. **Asynchronously fulfill the customer’s order** by:
    - Setting up a webhook
    - or Manually using the Stripe Dashboard
    - or Using a partner application
    - or Using a cron job to fetch recent events

I am in the dark with this two different workflows. From the sixth point in the README.md file, how the PaymentIntent confirmation is made? This is not by providing a callback URL (like PayPal for example). I think we have to create a webhook, isn't it?

Thanks to help me clarify the workflow

**Comment by domis86** [comment]
You are looking at the "asynchronous PaymentIntent flow" - which indeed requires webooks.
Please check te "synchronous" variant of the flow: https://stripe.com/docs/payments/payment-intents/web-manual

**Comment by 2ec0b4** [comment]
Thank you @domis86 
I missed the keyword "manual" from the README.md file and I was not able to find a link to this page from the stripe.com documentation
I made a pull request to update the README.md file: https://github.com/thephpleague/omnipay-stripe/pull/147
