### ISSUE TITLE
How do actually setup PaymentIntents?

### ISSUE THREAD

**Issue by ajarmoszuk** [thephpleague/omnipay-stripe#158]
There is no information that is relevant to the actual setup.

When using the tutorial from the readme I receive a "Call to undefined method Omnipay\Stripe\Gateway::confirm()" error which means that the function confirm doesn't actually exist?

Can someone put me on the right path here? 
I want to get SCA to work properly and it's been days now.

Thanks all.

**Comment by domis86** [comment]
Probably you used the normal gateway:
https://github.com/thephpleague/omnipay-stripe/blob/master/src/Gateway.php
instead of the PaymentIntents one:
https://github.com/thephpleague/omnipay-stripe/blob/master/src/PaymentIntentsGateway.php

**Comment by marbuser** [comment]
@domis86 I don't know if you are involved in this project, but how is anyone remotely supposed to know that at first glance when it comes to this package?

I don't know why but it feels like OmniPay and 95% of all the drivers for it have incredibly bad documentation and almost no information on how to use it even from StackOverflow. Makes you wonder how this package is so popular if no one knows how to use it. 🤔

**Comment by ajarmoszuk** [comment]
The documentation does exist, but it's stored in the gateway files themselves and you have to look for them. There should be some kind of alink in the README file that will take you there, or at least give you some more explanation. I've resolved my issue, and so I'm closing this.

**Comment by domis86** [comment]
@marbuser 

> I don't know if you are involved in this project, 

Im not owner of this project - just trying to help :)

> but how is anyone remotely supposed to know that at first glance when it comes to this package?

Unfortunately best way is to study the source code  - shouldnt be hard if you have IDE like Phpstorm (you can quickly follow to class/method definitions etc).

> I don't know why but it feels like OmniPay and 95% of all the drivers for it have incredibly bad documentation

Well there is opportunity - also for you - to change that :) Its open source so everyone can contribute - also to documentation.
