### ISSUE TITLE
How the stripe can be redirected to offsite payment gateway.?

### ISSUE THREAD

**Issue by amit4106udale** [thephpleague/omnipay-stripe#165]

**Comment by domis86** [comment]
Stripe is a payment gateway :)

Can you reword your question?

**Comment by amit4106udale** [comment]
@domis86 Currently, I am able to use the onsite stripe payment using the card details. But now I want to redirect the payment to the offsite stripe payment gateway like PayPal.

**Comment by domis86** [comment]
@amit4106udale 

> offsite stripe payment gateway like PayPal

Sorry, i think you are mixing some things. Stripe has nothing to do with Paypal :) They are different payment gateways

**Comment by amit4106udale** [comment]
@domis86 - I am just giving an example I am not mixing them.

I just want to redirect to the offsite stripe payment gateway. how can I do that?

**Comment by amit4106udale** [comment]
@domis86 - https://stripe.com/docs/payments/3d-secure
I am talking about this, I am unable to integrate it
