### ISSUE TITLE
Using direct charge with application fee and connect account

### ISSUE THREAD

**Issue by louis-l** [thephpleague/omnipay-stripe#174]
Hi there,

Im currently using [Stripe PHP](https://github.com/stripe/stripe-php) package to fire charge request like this:

```php
$result  = Charge::create(
	[
		'amount' => 10000,
		'currency' => 'AUD',
		'description' => 'Item description',
		'source' => 'the card token',
		'application_fee_amount' => 5000,
	],
	[
		'stripe_account' => 'connected_account_id'
	]
);
```

However, looking at the at the `setApplicationFee()` at https://github.com/thephpleague/omnipay-stripe/blob/master/src/Message/AuthorizeRequest.php#L195, it sets the param key as **applicationFee**, but not **applicationFeeAmount**.

Also, I cant find a way to pass **stripe_account** using this package.

Can anyone know if it is posible to use this package to achieve the charge request like above?

Thanks.

**Comment by alexsegura** [comment]
To specify a connected account, you need to use the `setConnectedStripeAccountHeader` method

https://github.com/thephpleague/omnipay-stripe/blob/fbf57b33c34f227695e83c1cc92d9844f88ed5e8/src/Message/AbstractRequest.php#L133

**Comment by louis-l** [comment]
Thanks @alexsegura 
Will try that out 👍
