### ISSUE TITLE
Not working with latest symfony/http-foundation

### ISSUE THREAD

**Issue by Metrakit** [thephpleague/omnipay-stripe#175]
Hi,

First of all, thanks for your package, it saved me lot of times in the past. I have just upgraded my Laravel app to Laravel 7 (the latest version) and it use the symfony/http-foundation v5 of symfony.

The package is going soon to support this new version of symfony/http-foundation ? 

Im getting this error :

```sh
Problem 1
    - Installation request for omnipay/stripe ^3.1 -> satisfiable by omnipay/stripe[v3.1.0].
    - Conclusion: remove symfony/http-foundation v5.0.7
    - Conclusion: don't install symfony/http-foundation v5.0.7
    - omnipay/stripe v3.1.0 requires omnipay/common ^3 -> satisfiable by omnipay/common[v3.0.0, v3.0.1, v3.0.2].
    - omnipay/common v3.0.0 requires symfony/http-foundation ^2.1|^3|^4 -> satisfiable by symfony/http-foundation[...
```

Thanks in advance 🚀

**Comment by barryvdh** [comment]
I've released omnipay-common with support for Symfony 5: https://github.com/thephpleague/omnipay-common/releases/tag/v3.0.3

**Comment by Metrakit** [comment]
Wow thanks for your good work @barryvdh ❤️
