### ISSUE TITLE
The currency parameter is required

### ISSUE THREAD

**Issue by Braunson** [thephpleague/omnipay-stripe#18]
I'm setting the currency parameter, however I'm still receiving this error
 ``The currency parameter is required``

```php
$pw = new PaymentWrapper( 'Stripe' );

...

$pw->initialize($processorParams);

$pw->setCreditCard([
      ...
]);

// Determine total order cost
$amount = 4000.00;
$currency = 'CAD';
$pw->purchase( $amount, $currency );
$pw->processResponse();
```

**Comment by cfreear** [comment]
What is ``PaymentWrapper``? It's not part of Omnipay and google hasn't turned anything up...

**Comment by kayladnls** [comment]
Ditto to what @cfreear said. What is PaymentWrapper?

If it's just a wrapper around Omnipay, then the purchase method requires an associative array of parameters. 

Let me know of you have further problems

**Comment by cfreear** [comment]
The php league has a great basic example [here](http://omnipay.thephpleague.com/simple-example/).

**Comment by Braunson** [comment]
Great thanks @kayladnls @cfreear !
