### ISSUE TITLE
Replacing guzzle package.

### ISSUE THREAD

**Issue by paroxp** [thephpleague/omnipay-stripe#19]
Hi there.

Just got few "warnings" while installing your package, basically saying:

```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

As you're requiring: guzzle/http https://packagist.org/packages/guzzle/http

Probably not a big issue just yet, but it may be worth considering a switch ;)

Thanks.

**Comment by kayladnls** [comment]
Thanks! I'm already looking into it. It will be fixed shortly.
