### ISSUE TITLE
3DS - Create card issue with isRedirect()

### ISSUE THREAD

**Issue by AntoineLemaire** [thephpleague/omnipay-stripe#191]
Hi there
I'm facing a issue when creating a card from a source.

I get the source from javascript :

```
var stripe = Stripe('pk_test_xxxxxxxxxxxxxxxxxxxxx');
stripe.createSource({
    type: 'card',
    token: 'tok_visa',
}).then(function(result) {
    // get source from result json
});
```
![image](https://user-images.githubusercontent.com/2025537/91610667-ff31f480-e979-11ea-9904-ef9880a14909.png)

Then I use the gateway to create a card

```
$response = $gateway->createCard([
    'customerReference' => 'cus_Hv3tbgOGRgmaur',
    'source'            => 'src_1HLDkmELCR82aCU0aKqaFWIL',
])->send();
```
As response, I got that
![image](https://user-images.githubusercontent.com/2025537/91610888-62238b80-e97a-11ea-8071-efca9a4f47d6.png)

The `data['card']['three_d_secure']` is `optional`, but I don't have any `data['redirect']['url']`

So if I do

```
if ($response->isSuccessful()) {
    // Response is not successful, because of isRedirect() === true (because of cardCan3DS() === true)
} else if($response->isRedirect()) {
    $response->redirect(); // Will fail, because redirect Url is null
} else {
    // 
}
```

If I remove the `isRedirect()` condition inside `isSuccessful()`, my card is well created and I can attach it to my user without any issue

![image](https://user-images.githubusercontent.com/2025537/91610947-7cf60000-e97a-11ea-81dc-2abd24144287.png)

Am I doing something wrong?

**Comment by domis86** [comment]
```
stripe.createSource({
```

Lets see docs about this method https://stripe.com/docs/js/tokens_sources/create_source - they link to https://stripe.com/docs/api#sources , and there there is link to https://stripe.com/docs/sources :

```
As of September 2019, a regulation called Strong Customer Authentication (SCA) requires businesses in Europe to request additional authentication for online payments. Businesses in Europe must start building their Stripe integrations with the Payment Intents and Payment Methods APIs instead of the Sources API to be ready for these rule changes.
```

As you see the "Sources API" in Stripe is deprecated - you should use Payment Intents instead.

**Comment by AntoineLemaire** [comment]
Thanks you @domis86 for showing me that ! The project was created before in 2018 and we never migrate.
I'm gonna have a look about that, thanks for helping me!
