### ISSUE TITLE
Charge doesnt support destination parameter

### ISSUE THREAD

**Issue by m-naw** [thephpleague/omnipay-stripe#20]
As I work with Stripe Connect there are to way of creating payments 

https://stripe.com/docs/connect/payments-fees

Currently lib supports only direct charge with application fee. It would be great to support destination parameter. Also source parameter seems to be not supported.

Is it possible to add support of different charging types ?

**Comment by qlik** [comment]
I think this should fix the problem
https://github.com/thephpleague/omnipay-stripe/pull/22

**Comment by delatbabel** [comment]
The PR has been merged so I will close this.
