### ISSUE TITLE
Wrong behavior for incorrect data

### ISSUE THREAD

**Issue by aimeos** [thephpleague/omnipay-stripe#28]
The Stripe provider throws an exception if the the server returns that one of the card details was invalid.

According to the docs, isSuccessful() should return false and $response->getMessage() should return the string that should be displayed to the user.

**Comment by cfreear** [comment]
What is the exception you are receiving and could you provide an example of the card data you are passing incorrectly?

**Comment by aimeos** [comment]
The exceptions happen if obviously invalid data is entered like a too short card number or a expiry date in the past. Maybe this is checked upfront and an exception is then thrown without a request being made.

If this is a valid behavior, the Omnipay documentation should be updated because it says that exceptions should not be displayed to the customer.

**Comment by andrewtweber** [comment]
http://omnipay.thephpleague.com/api/cards/

> If you submit credit card details which are obviously invalid (missing required fields, or a number which fails the Luhn check), InvalidCreditCardException will be thrown. You should validate the card details using your framework’s validation library before submitting the details to your gateway, to avoid unnecessary API calls.

That is valid behavior and the documentation matches. Just catch those exceptions and display an error message to the user.

**Comment by aimeos** [comment]
Would be great if someone would extend the documentation about error handling so others don't fall into this trap either: https://github.com/thephpleague/omnipay#error-handling

**Comment by andrewtweber** [comment]
Well it does say that exceptions are possible, and suggests wrapping the whole thing in a try/catch anyway. I'm not a member of Omnipay/the league btw.
