### ISSUE TITLE
Issue with amount parameter.

### ISSUE THREAD

**Issue by daylerees** [thephpleague/omnipay-stripe#3]
Hey guys,

I'm issuing a payment with the following options array:

``` php
$options = [
    'amount'            => '10.00',
    'cardReference'     => 'cus_REAL_REFERENCE',
    'currency'          => 'GBP'
];

$gateway->purchase($options)->send();
```

and here's the request as shown in the Stripe back-end.

``` json
{
    "amount": 1000,
    "currency": "gbp",
    "description": "",
    "capture:" true,
    "customer": "cus_REAL_REFERENCE"
}
```

As you can see, the 10.00 is being interpreted as 1000 GBP. Am I doing something wrong? I've tried strings and floats as the amount parameter.

**Comment by amit4106udale** [comment]
It is sill there?
