### ISSUE TITLE
Logic for customer and source have changed

### ISSUE THREAD

**Issue by delatbabel** [thephpleague/omnipay-stripe#30]
From the Stripe API reference:

... If you also pass a customer ID, the source must be the ID of a source belonging to the customer. Otherwise, if you do not pass a customer ID, the source you provide must either be a token, like the ones returned by Stripe.js, or a dictionary containing a user's credit card details, with the options described below.

(Inference: you cannot pass a customer ID and the customer's credit card details, you must either pass a customer ID and a card token, or a customer ID without a card token, or card data without a customer ID).

**Comment by AJSturrock** [comment]
This would be really helpful for us. Would the above pull request enable you to pass over just the customerReference (therefore using the customers default card rather than having to declare a specific card?).

**Comment by kayladnls** [comment]
@AJSturrock yes, it should allow that, assuming there is no cardData or cardReference present.

**Comment by AJSturrock** [comment]
@kayladnls great, when do you expect this can be pulled in? :)

**Comment by delatbabel** [comment]
@AJSturrock -- @kayladnls has asked me to do test cases for my PR which I will do in a week or so when I return from holidays.

**Comment by AJSturrock** [comment]
Awesome :+1: have a nice holiday!

**Comment by delatbabel** [comment]
I have just pushed the test cases.
