### ISSUE TITLE
FR: Method for passing receipt_email

### ISSUE THREAD

**Issue by nathanpitman** [thephpleague/omnipay-stripe#32]
It's really important for our accounts dept to be able to easily identify transactions in Stripe by customer email but the Omnipay Stripe implementation doesn't appear to support passing on receipt_email or even customer email (if we're using a token and not passing card details directly).

I notice there [some discussion pertaining to this previously](https://github.com/thephpleague/omnipay-stripe/pull/5) but it didn't appear to go anyway... any thoughts?

**Comment by devcflynn** [comment]
I am having this same issue? No receipts are being sent out.

**Comment by grupp3pvt15** [comment]
Same. Also trying to pass a statement_descriptor fails and shows as null in logs. Very restrictive library.

**Comment by davidrushton** [comment]
Just came across this and managed to work out a local solution. For anyone else interested:

```
$gateway = Omnipay::create('Stripe');
$gateway->setApiKey('');

$payment = $gateway->purchase([
	'amount' => $amount,
	'currency' => 'GBP',
	'token' => ''
]);

$data = $payment->getData();
$data['receipt_email'] = 'example@example.com';

$response = $payment->sendData($data);
```

**Comment by Scrivs** [comment]
@davidrushton Oh dear lord you have saved me. I was banging my head trying to get this to work for weeks and figured I would finally Google it and came upon your solution. I owe you donuts!

**Comment by davidrushton** [comment]
@Scrivs Haha - no donuts required, but glad you got it working :thumbsup:

**Comment by delatbabel** [comment]
A PR could be submitted to fix this. Just sayin'.
