### ISSUE TITLE
CreateCustomer doesn't return proper card token 

### ISSUE THREAD

**Issue by warkior** [thephpleague/omnipay-stripe#41]
Hi there, 
I've tried both createCustomer and createCard with no customer attached to try and retrieve a customer ID and card ID. The code seems to only return the customer ID for both fields. 
```
    $sendData = [
            'card' => new OmniPayCreditCard( $cardData->all() ), // OmniPayCreditCard is just a renamed instance of the Omnipay CreditCard object.
        ];
        \Log::debug([ __METHOD__ => $sendData]);
        $response = $this->gateway->createCustomer($sendData)->send();

        if ($response->isSuccessful()) {

            $customer_id = $response->getCustomerReference();
            \Log::debug([ __METHOD__ => $customer_id]);

            $card_id     = $response->getCardReference();
            \Log::debug([ __METHOD__ => $card_id]);

            return [
                'card_id'     => $card_id,
                'customer_id' => $customer_id,
            ];

        } 
```

When the code returns, the $customer_id and $card_id variables are identical, and appear to contain the customer ID.

**Comment by delatbabel** [comment]
I haven't forgotten about this but I haven't had time to look at it yet either. I will hopefully get to this next week.  IIRC it was deliberate that attempting to create a card without a customer attached returned the customer token not the card token. This is for a couple of reasons:

* Historically the original version of this gateway did not implement createCustomer, only createCard. In fact it just created a customer with a single card token and returned the customer token.
* With Stripe it's possible to pay using only a customer token and no card token provided that that customer has one and only one card registered (or a default card).  I think that at the time it wasn't possible to pay using just a card token without also providing the customer token.

I know that I've had several goes at ensuring that this works correctly, and as transparently as possible, even though the various methods may not always return what you expect (i.e. may return a customer token when you may expect a card token, etc).

**Comment by delatbabel** [comment]
This is what works for me and I believe to be the correct flow:

```php
    $response = $gateway->createCustomer(array(
        'description'       => 'Test Customer',
        'email'             => 'test123@example.com',
    ))->send();
    if ($response->isSuccessful()) {
        echo "Gateway createCustomer was successful.\n";

        // Find the card ID
        echo "\nfetch customer ID\n=================\n";
        $customer_id = $response->getCustomerReference();
        echo "Customer ID = " . $customer_id . "\n";

    } else {
        echo "Gateway createCustomer failed.\n";
        echo "Error message == " . $response->getMessage() . "\n";
    }
```

The createCard request now follows the above call. You do not need to call updateCustomer() to add a card to a customer, instead you should use createCard()

Note that this is just a cut and paste from the code in the CreateCardRequest class docblock, it's all documented there.

```php
    $new_card = new CreditCard(array(
             'firstName'    => 'Example',
             'lastName'     => 'Customer',
             'number'       => '5555555555554444',
             'expiryMonth'  => '01',
             'expiryYear'   => '2020',
             'cvv'          => '456',
             'email'                 => 'customer@example.com',
             'billingAddress1'       => '1 Lower Creek Road',
             'billingCountry'        => 'AU',
             'billingCity'           => 'Upper Swan',
             'billingPostcode'       => '6999',
             'billingState'          => 'WA',
 ));

 // Do a create card transaction on the gateway
 $response = $gateway->createCard(array(
     'card'              => $new_card,
     'customerReference' => $customer_id,
 ))->send();
 if ($response->isSuccessful()) {
     echo "Gateway createCard was successful.\n";
     // Find the card ID
     $card_id = $response->getCardReference();
     echo "Card ID = " . $card_id . "\n";
 }
```
