### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by matgargano** [thephpleague/omnipay-stripe#51]

**Comment by cfreear** [comment]
This package doesn't require guzzle/guzzle directly but does through [thephpleague/omnipay-common](https://github.com/thephpleague/omnipay-common). Replacing guzzle/guzzle is part of the [Omnipay 3 roadmap](https://github.com/thephpleague/omnipay/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AV3.0) and when omnipay-common is updated then the gateway packages will be updated to follow suit.

**Comment by delatbabel** [comment]
This is on the roadmap for version 3.
