### ISSUE TITLE
CreatePlanRequest not converting floats to integer

### ISSUE THREAD

**Issue by zanderwar** [thephpleague/omnipay-stripe#59]
This is taken care of in `purchase()` but neglected in CreatePlanRequest

```
array(1) { ["error"]=> array(3) { ["type"]=> string(21) "invalid_request_error" ["message"]=> string(23) "Invalid integer: 552.82" ["param"]=> string(6) "amount" } }
```

**Comment by delatbabel** [comment]
Can you submit a PR for this?

**Comment by barryvdh** [comment]
@zanderwar why the thumbs down?

**Comment by zanderwar** [comment]
Ah I had responded on the other issue saying I had no time, this was just a reflection of that, sorry if it seemed off :P
