### ISSUE TITLE
CreateSubscriptionRequest MetaData missing

### ISSUE THREAD

**Issue by zanderwar** [thephpleague/omnipay-stripe#60]
```php
$response = $gateway->createSubscription(
                    array(
                        'customerReference' => $customerReference,
                        'plan'              => $planID,
                        'metadata'          => array(
                            'exhibitor_id' => $exhibitor->ID // confirmed this ID is of type integer and value of 1073
                        )
                    )
                )->send();
```

Issue: Not sent to Stripe
Proof:

![screen shot 2016-11-08 at 1 34 58 pm](https://cloud.githubusercontent.com/assets/13566916/20087142/a2811b80-a5c1-11e6-9209-bb346f148b20.png)

**Comment by delatbabel** [comment]
OK what's the fix for this?  Can you submit a PR?

**Comment by zanderwar** [comment]
My fix, personally was making the plan ID include the ID of the exhibitor then have my webhook regex it out of it, as each plan is created dynamically and only one person would ever be subscribed to it (instalment plans with varied/never-the-same amounts) so this was ideal for my scenario.

Unfortunately I don't get paid enough to fix other peoples issues, so you're welcome to submit your own PR or close this issue and pretend nothing happened, whatever you think is more suitable to the longevity :)

**Comment by zanderwar** [comment]
I fixed the image

**Comment by zanderwar** [comment]
Why was this closed? It still doesn't submit meta data.....

**Comment by mikealmond** [comment]
@zanderwar It was merged into master, but hasn't been tagged yet. You'll have to use `dev-master` in your `composer.json` file to test it.

**Comment by zanderwar** [comment]
Thanks :)

**Comment by delatbabel** [comment]
Yes, I'm still waiting for confirmation that the dev branch works in production before I tag it for release.
