### ISSUE TITLE
PHP notice error: undefined index `code` on Message/Response.php#L308

### ISSUE THREAD

**Issue by acstll** [thephpleague/omnipay-stripe#62]
Hi there,

I'm getting this error in the context of the Craft Commerce Plugin, on the last step of checkout.

The data I feed to the form is correct (a valid Stripe token), and it works fine with the Test API Keys. So the error only happens when working with the Live Keys.

https://github.com/thephpleague/omnipay-stripe/blob/master/src/Message/Response.php#L308

Here's an example of the data I get using Stripe.js (I'm "blurring" the token because real card)

```js
{
  id: "tok_19J5meHOW6ChjHQ7djwPxxxx",
  object: "token",
  card: Object,
  client_ip: "83.32.118.217",
  created: 1479926872,
  livemode: true,
  type: "card",
  used: false
}
```

Any ideas?

Please let me know If I should be asking somewhere else.

Thank you!

**Comment by acstll** [comment]
Ok, I checked Stripe's logs and found the cause of the error:

```
error: {
  type: "invalid_request_error"
  message: "Amount must be at least 50 cents"
  param: "amount"
}
```

Still this looks like a bug.

**Comment by kinglozzer** [comment]
Just encountered this too. The `code` key is optional (in fact, `type` is the only key guaranteed to be present): https://stripe.com/docs/api#errors. Looks like this code just needs an `isset()` (note, we should also add one to `getMessage()` as the `message` key is also optional). cc @delatbabel

**Comment by delatbabel** [comment]
OK can someone submit a PR for this please?

**Comment by acstll** [comment]
Yes, I could try a PR, but I have a doubt… documentation for both `getCode()` and `getMessage()` methods says `Returns null if the request was successful.`, but that won't be true anymore if we add `isset()` to them. So wouldn't this change cause greater bugs? I mean, is people relying on getting `null` from any of these methods to check whether the transaction was successful or not?

**Comment by delatbabel** [comment]
I doubt that there would be any breakages.  The getCode() and getMessage() functions in other gateways don't always return null on a successful request, and furthermore there is a separate isSuccessful() function to determine the success / failure of the request which is the correct function to use to determine failure status.

**Comment by judgej** [comment]
Should the core documentation be amended then, to state that code and message may be returned if available, regardless of success result?

**Comment by kinglozzer** [comment]
I’ve created a PR here: https://github.com/thephpleague/omnipay-stripe/pull/67. These two methods will still always return `null` on success, that behaviour hasn’t been changed.

**Comment by miguelsolano** [comment]
Getting this err:
Undefined index: code

**Comment by kinglozzer** [comment]
@miguelsolano Make sure you’re running v2.4.2 or newer

**Comment by miguelsolano** [comment]
You are absolutely right, it appears that Craft Cms is running a later version. I submitted a ticket and they are currently testing 💯
