### ISSUE TITLE
createCustomer support for source

### ISSUE THREAD

**Issue by nickwuk** [thephpleague/omnipay-stripe#90]
I've tried passing the extra parameter 'source' to the function createCustomer and setting it to the token returned by Stripe 'Checkout', as shown [here](https://stripe.com/docs/api#create_customer), but it's not sent. Then I've read [here](https://stackoverflow.com/questions/22924994/omnipay-stripe-extra-parameters) that omnipay-stripe doesn't support extra parameters.

Can this work around method be used instead: 
`$response = $gateway->createCustomer(array(
      'description'       => 'Test Customer',
      'email'             => 'test123@example.com',
 ));
$data = $request->getData();
$data['source'] = 'tok_1234oVJjPoOHXFyktY79rGyk';
$response = $request->sendData($data);`
It seems to work.

Would be great if this function could be extended to support the 'source' parameter.

Once the customer has been created the token can't be re-used for the purchase so I want to use the customer_id instead of the token in the purchase request, however I run into the issue explained [here](https://github.com/thephpleague/omnipay-stripe/issues/6). The solution described seems to involve creating a card, but I don't want to handle any card data for PCI compliance reasons. 

It works if I only use the token in the purchase request and not when creating the customer, but I want to create a susbscription and to do that I believe the customer first requires a source/card.

**Comment by delatbabel** [comment]
The CreateCustomer message does indeed support the source parameter:

See: https://github.com/thephpleague/omnipay-stripe/blob/master/src/Message/CreateCustomerRequest.php

What evidence do you have that indicates that the source parameter is not sent?  The unit tests seem to indicate that it is.

**Comment by nickwuk** [comment]
Please accept my apologies, having setup a new bare bones test, I can confirm it DOES work! I've tested the following code to create the customer with card details attached, then create a subscription using the 'plan' and 'customerReference' parameters, and to finally charge the card using the customerReference (isSuccessful check and error checking omitted for clarity):

```
        $response = $gateway->createCustomer(array(
		 'description'       => 'Test Customer',
		 'email'             => $_POST['stripeEmail'],
		 'source'  => $token
	 ))->send();

	 $response = $gateway->createSubscription(array(
		 "customerReference" => $customer_id,
		 'plan'	=> 'plan_name',
	 ))->send();

	$transaction = $gateway->purchase(array(
					  'amount'   => '5.00',
					  'currency' => 'gbp',
					  'receipt_email' => 'test@test.com',
					  "description" => 'Test Order',
					  'customerReference' => $customer_id,
	));
```
